IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID('AgregarAutor') AND type in ('P', 'PC'))
	EXEC('CREATE PROC AgregarAutor AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROC AgregarAutor
	@Nombre AS VARCHAR(80),
	@Ciudad AS INT,
	@Sexo AS VARCHAR(2),
	@Error AS INT OUT
AS
BEGIN
BEGIN TRY
	BEGIN TRAN
		INSERT INTO Autor VALUES(@Nombre,@Ciudad,@Sexo)
		SET @Error = 0
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
	SET @Error = ERROR_NUMBER()
END CATCH
END