IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID('EliminarAutor') AND type in ('P', 'PC'))
	EXEC('CREATE PROC EliminarAutor AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROC EliminarAutor
	@IdAutor AS INT,
	@Error AS INT OUT
AS
BEGIN
BEGIN TRY
	BEGIN TRAN
		DELETE Autor WHERE IdAutor = @IdAutor
		SET @Error = 0
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
	SET @Error = ERROR_NUMBER()
END CATCH
END