IF NOT EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID('EliminarLibro') AND type in ('P', 'PC'))
	EXEC('CREATE PROC EliminarLibro AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROC EliminarLibro
	@IdLibro AS INT,
	@Error AS INT OUT
AS
BEGIN
BEGIN TRY
	BEGIN TRAN
		DELETE Libro WHERE IdLibro = @IdLibro
		SET @Error = 0
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
	SET @Error = ERROR_NUMBER()
END CATCH
END